[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuration pour l'environnement de staging
[context.staging]
  command = "npm run build:staging"
  environment = { VITE_ENV = "staging" }

# Configuration pour l'environnement de production
[context.production]
  command = "npm run build"
  environment = { VITE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 